---
- hosts: localhost
  remote_user: vagrant
  sudo: yes
  vars_files:
    - 'roles/users/vars/vars.yml'
  roles:
    - users
- hosts: localhost
  remote_user: core
  vars_files:
    - 'roles/ssh_keys/vars/vars.yml'
  roles:
    - ssh_keys
- hosts: coreos-cluster
  gather_facts: False
  remote_user: core
  roles:
    - defunctzombie.coreos-bootstrap 
- hosts: coreos-cluster
  remote_user: core
  roles:
    - test
